diffusion_img_size: ???
diffusion_depth_size: ???
diffusion_num_channels: ???
cond_dim: ???
dim_mults: [1,2,4,8]
results_folder: ???
load_milestone: False
batch_size: 18
num_workers: 20
logger: wandb
objective: pred_x0

save_and_sample_every: 1000

denoising_fn: Unet3D
train_lr: 1e-4
timesteps: 300 
sampling_timesteps: 300 
loss_type: l1 
train_num_steps: 50001 
gradient_accumulate_every: 2 
ema_decay: 0.995 
amp: False 
num_sample_rows: 1
gpus: 0