data_type:  ???

cond_dim: ??? 
types: ???

diffusion_img_size: ???
diffusion_depth_size: ???
diffusion_num_channels: ???
dim_mults: [1,2,4,8]
batch_size: ???

test_txt_dir: ''
dataset_root_dir: ???
target_img_path: ???
target_label_path: ???

load_milestone: False
num_workers: 20
save_and_sample_every: 1000 
denoising_fn: Unet3D

train_lr: 1e-4
timesteps: 300 
sampling_timesteps: 300 
loss_type: l1 
train_num_steps: 700000 
gradient_accumulate_every: 2
ema_decay: 0.995 
amp: False
num_sample_rows: 1
gpus: 0


attention_resolutions: 32,16,8
class_cond: false
diffusion_steps: 1000
learn_sigma: true
noise_schedule: linear
num_channels: 256
num_head_channels: 64
num_heads: 4
num_res_blocks: 2
resblock_updown: true
use_fp16: false
use_scale_shift_norm: true
classifier_scale:  0   
lr_kernel_n_std: 2
num_samples: 100
show_progress: true
timestep_respacing: '300'
use_kl: false
predict_xstart: false
rescale_timesteps: false
rescale_learned_sigmas: false
classifier_use_fp16: false
classifier_width: 128
classifier_depth: 2
classifier_attention_resolutions: 32,16,8
classifier_use_scale_shift_norm: true
classifier_resblock_updown: true
classifier_pool: attention
num_heads_upsample: -1
channel_mult: ''
dropout: 0.0
use_checkpoint: false
use_new_attention_order: false
clip_denoised: true
use_ddim: false
latex_name: RePaint
method_name: Repaint
image_size: 256
model_path: ???

name: lidc_hist_3d
inpa_inj_sched_prev: true
n_jobs: 1
print_estimated_vars: true
inpa_inj_sched_prev_cumnoise: false

schedule_jump_params:
  t_T: 300
  n_sample: 1
  jump_length: 10 
  jump_n_sample: 10

